db:
  uri: mongodb://mongo:27017 # Connection URI to your MongoDB Server
  name: peppercord # Name of the DB on your PepperCord server
discord:
  api:
    token: UghqQolQCODamh1fS7B7DKkE.tJEE4u.TnJJbmoBbyscPFViH4OSOCX2Fyf # Token for your bot. Self bots don't work.
  commands:
    prefix: '?' # Prefix for all commands.
    cooldown:
      rate: 6 # Amount of commands that can be executed every per
      per: 10
web:
  base: https://www.regulad.xyz/PepperCord # Base domain for donate button and more
  github: https://github.com/regulad/PepperCord # GitHub repo site
